### ISSUE TITLE
where can i get the trained model

### ISSUE THREAD

**Issue by cooper12121** [truas/BSD_Extractor#2]
Excuse me,i want use your model to transform the raw txt to your output format,wher can i get the trained model of your project,i can't find it in the deepblue resposity 
![image](https://github.com/truas/MSSA/assets/55910045/1058101b-a97a-442e-99ba-7184135abd7e)
can you help me? thank you very much

**Comment by truas** [comment]
Hi @cooper12121 , 

All the models are zipped in their respective folders (for Wikipedia 2010 and 2018).
Although if you have the raw txt you can also run any word embeddings algorithms and the output will be a model indexing the synset-key you have trained.

In any case the models are in the zip files you listed. On the readme of this repository you will also find the hyperparameter these models were generated.  Please let me know if you cannot download/use them. I can try to recover from my backup/storage
